#!/usr/bin/env bash
#
# Tests for scripts/full-test.sh.          bash scripts/tests/full-test.test.sh
#
# The script under test raises a docker stack and rewrites three env files, so
# none of that is allowed to be real here. Each case copies the script into a
# throwaway git repository with an example env file and empty compose files,
# and runs it with `docker`, `npm`, `curl`, `trivy`, `openssl` and `sleep`
# replaced by stubs that write what they were asked to a log.
#
# PATH is exactly two directories — the stubs, and symlinks to an allow-list
# of real tools. /usr/bin and /bin are NOT on it: the real docker lives there,
# and on a developer's machine it is usually running the very stack this
# script must never touch. A stub that is asked for something it was not told
# to expect logs UNEXPECTED and exits 99, and the last case fails if that
# happened anywhere.
#
# PPP_FULLTEST_PORTS is pointed at a port nothing listens on, because the real
# four are taken on any machine with a stack up — which is where these tests
# are most likely to be run.
#
# PPP_TEST_SCRIPT points the suite at another copy of the script, which is how
# a deliberately broken one is shown to fail.

set -uo pipefail
export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
SCRIPT="${PPP_TEST_SCRIPT:-$REPO_ROOT/scripts/full-test.sh}"

BASE="$(mktemp -d "${TMPDIR:-/tmp}/ppp-fulltest-test.XXXXXX")"
LISTENER=""
trap '[ -z "$LISTENER" ] || kill "$LISTENER" 2>/dev/null; rm -rf "$BASE"' EXIT

# ----- the two PATH directories ------------------------------------------------
ALLOW="bash sh env git node python3 sed awk grep sort tail head cat cp mv rm
  mkdir mktemp date diff tr cut wc printf chmod touch ls dirname basename readlink
  timeout tee cmp stat id find xargs uname true false kill"
mkdir -p "$BASE/bin" "$BASE/stubs"
for tool in $ALLOW; do
  p="$(type -P "$tool")" || { echo "cannot run: $tool is not installed" >&2; exit 1; }
  ln -s "$p" "$BASE/bin/$tool"
done

cat >"$BASE/stubs/docker" <<'STUB'
#!/usr/bin/env bash
printf 'docker %s\n' "$*" >>"$STUB/log"
S="$STUB/state"
case "${1:-}" in
  compose)
    [ "${2:-}" != "version" ] || exit 0
    verb=""
    for a in "$@"; do case "$a" in up|down|logs) verb="$a" ;; esac; done
    # What compose would see: the caller's environment, and the env file as it
    # is at this moment.
    printf 'SEEN %s DB_PASSWORD=%s PPP_TAG=%s DATA_ROOT=%s COMPOSE_PROJECT_NAME=%s last-line=%s\n' "$verb" \
      "${DB_PASSWORD-unset}" "${PPP_TAG-unset}" "${DATA_ROOT-unset}" "${COMPOSE_PROJECT_NAME-unset}" \
      "$(tail -1 .env.docker 2>/dev/null)" >>"$STUB/log"
    case "$verb" in
      up) [ ! -e "$S/up-fail" ] || exit 1; mkdir -p "$DATA_ROOT/db"; exit 0 ;;
      logs) echo "container logs"; exit 0 ;;
      down) [ ! -e "$S/term-on-down" ] || kill -TERM "$PPID"; exit 0 ;;
    esac ;;
  ps)
    case " $* " in
      *" -aq "*) cat "$S/ps-label" 2>/dev/null; exit 0 ;;
      *" -a "*) cat "$S/ps" 2>/dev/null; exit 0 ;;
    esac ;;
  network)
    case "${2:-}" in
      ls) cat "$S/networks" 2>/dev/null; exit 0 ;;
      rm) exit 0 ;;
    esac ;;
  rm) exit 0 ;;
  inspect) if [ -f "$S/owner" ]; then cat "$S/owner"; else echo "ppp-fulltest"; fi; exit 0 ;;
  run)
    case " $* " in
      *" rm -rf /o/data "*) [ ! -e "$S/rm-fail" ] || exit 1; rm -rf "${4%:/o}/data"; exit 0 ;;
      *"command -v npm"*) [ -e "$S/npm-in-image" ] && exit 0; exit 1 ;;
      *"prisma --version"*) exit 0 ;;
    esac ;;
esac
echo "unexpected: docker $*" >&2
printf 'UNEXPECTED docker %s\n' "$*" >>"$STUB/log"
exit 99
STUB

cat >"$BASE/stubs/npm" <<'STUB'
#!/usr/bin/env bash
printf 'npm %s\n' "$*" >>"$STUB/log"
S="$STUB/state"
if [ "${1:-} ${2:-}" = "run -s" ]; then
  script="${3:-}"
  case "$script" in
    typecheck|check:links|verify:models|verify:upload|verify:import|verify:queue|verify:frr|verify:benefits|verify:catalog|verify:api|probe:security) ;;
    check:secrets)
      # The secret scanner has to see the developer's own env files.
      printf 'SCANNED %s\n' "$(tail -1 .env 2>/dev/null)" >>"$STUB/log" ;;
    env:container)
      # As scripts/use-container-env.ts does: the old .env becomes .env.backup.
      if [ -f .env ]; then cp .env .env.backup; fi
      echo "# Generated by npm run env:container" >.env ;;
    *) script="" ;;
  esac
  if [ -n "$script" ]; then
    if [ -e "$S/fail-$script" ]; then echo "this one fails"; exit 1; fi
    if [ "$(cat "$S/term-during" 2>/dev/null)" = "$script" ]; then kill -TERM "$PPID"; fi
    exit 0
  fi
fi
echo "unexpected: npm $*" >&2
printf 'UNEXPECTED npm %s\n' "$*" >>"$STUB/log"
exit 99
STUB

cat >"$BASE/stubs/curl" <<'STUB'
#!/usr/bin/env bash
printf 'curl %s\n' "$*" >>"$STUB/log"
case " $* " in
  *" http://localhost:3000/api/health "*) [ ! -e "$STUB/state/unhealthy" ] || exit 7; echo '{"ok":true}'; exit 0 ;;
esac
echo "unexpected: curl $*" >&2
printf 'UNEXPECTED curl %s\n' "$*" >>"$STUB/log"
exit 99
STUB

cat >"$BASE/stubs/openssl" <<'STUB'
#!/usr/bin/env bash
case "$*" in
  "rand -base64 32") echo "stub-random-base64"; exit 0 ;;
  "rand -hex 24") echo "stub-random-hex"; exit 0 ;;
esac
printf 'UNEXPECTED openssl %s\n' "$*" >>"$STUB/log"
exit 99
STUB

printf '#!/usr/bin/env bash\nprintf "trivy %%s\\n" "$*" >>"$STUB/log"\n[ "$1" = "fs" ] || { printf "UNEXPECTED trivy %%s\\n" "$*" >>"$STUB/log"; exit 99; }\nexit 0\n' >"$BASE/stubs/trivy"
printf '#!/usr/bin/env bash\nexit 0\n' >"$BASE/stubs/sleep"
chmod +x "$BASE"/stubs/*
mkdir "$BASE/stubs-notrivy" "$BASE/stubs-cpfail"
cp -p "$BASE"/stubs/* "$BASE/stubs-cpfail/"
# A cp that runs out of disk halfway through saving .env.docker.
printf '#!/usr/bin/env bash\nfor a in "$@"; do last="$a"; done\ncase "$last" in\n  */ppp-full-test-saved/.env.docker*) echo "half a fi" >"$last"; [ ! -e "$STUB/state/kill-during-save" ] || kill -KILL "$PPID"; echo "cp: write error: No space left on device" >&2; exit 1 ;;\nesac\nexec %q "$@"\n' "$BASE/bin/cp" >"$BASE/stubs-cpfail/cp"
chmod +x "$BASE/stubs-cpfail/cp"
cp -p "$BASE"/stubs/* "$BASE/stubs-notrivy/"; rm "$BASE/stubs-notrivy/trivy"

# A port nothing listens on, and one something does.
FREE_PORT="$(python3 -c 'import socket; s = socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1])')"
python3 -c '
import socket, sys, time
s = socket.socket(); s.bind(("127.0.0.1", 0)); s.listen(8)
open(sys.argv[1], "w").write(str(s.getsockname()[1]))
time.sleep(600)' "$BASE/busy-port" &
LISTENER=$!
for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do [ -s "$BASE/busy-port" ] && break; sleep 0.1; done
BUSY_PORT="$(cat "$BASE/busy-port")"

# ----- per-case sandbox -------------------------------------------------------
T=""; N=0
new_sandbox() {
  [ -z "$T" ] || cat "$T/stub/log" >>"$BASE/all-logs" 2>/dev/null
  N=$((N + 1)); T="$BASE/s$N"
  mkdir -p "$T/repo/scripts" "$T/repo/node_modules" "$T/stub/state" "$T/home" "$T/tmp"
  : >"$T/stub/log"
  git init -q -b main "$T/repo"
  cp "$SCRIPT" "$T/repo/scripts/full-test.sh"
  ( cd "$T/repo" || exit 1
    : >docker-compose.prod.yml; : >docker-compose.build.yml; : >docker-compose.test.yml
    printf '%s\n' 'DB_PASSWORD="CHANGE-ME"' 'PPP_REGISTRY="ghcr.io/octo"' 'PPP_TAG="latest"' 'DATA_ROOT="./data"' >.env.docker.example
    printf '%s\n' '# the developer'"'"'s own' 'MINE=dev-env' >.env; chmod 600 .env
    printf '%s\n' 'MINE=dev-env-backup' >.env.backup; chmod 640 .env.backup
    printf '%s\n' 'MINE=dev-env-docker' 'PPP_TAG="v0.2.0"' >.env.docker; chmod 600 .env.docker )
  SAVED="$T/repo/.git/ppp-full-test-saved"
  LOGS="$T/out"
  STUBS="$BASE/stubs"; EXTRA=()
  ENV0="$(envsum)"
}

# Content and mode of each of the three files, or that it is not there.
envsum() {
  local f
  for f in .env .env.backup .env.docker; do
    if [ -e "$T/repo/$f" ]; then
      echo "$f $(cksum <"$T/repo/$f") $(stat -c %a "$T/repo/$f")"
    else
      echo "$f absent"
    fi
  done
}

# ft [args…] — run the script; the transcript lands in $OUT, the status in $RC.
ft() {
  ( cd "$T/repo" && timeout 60 env -i PATH="$STUBS:$BASE/bin" HOME="$T/home" TMPDIR="$T/tmp" STUB="$T/stub" \
      GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null PPP_FULLTEST_OUT="$LOGS" \
      PPP_FULLTEST_PORTS="$FREE_PORT" PPP_FULLTEST_HEALTH_TIMEOUT=1 "${EXTRA[@]}" \
      bash scripts/full-test.sh "$@" </dev/null ) >"$T/transcript" 2>&1
  RC=$?
  OUT="$(cat "$T/transcript")"
}

# ----- assertions ---------------------------------------------------------------
PASSED=0; FAILED=0; CASE=""; CASE_OK=1; DETAIL=""; OUT=""
t() { end_case; CASE="$1"; CASE_OK=1; DETAIL=""; }
end_case() {
  [ -n "$CASE" ] || return 0
  if [ "$CASE_OK" -eq 1 ]; then
    PASSED=$((PASSED + 1)); echo "ok   $CASE"
  else
    FAILED=$((FAILED + 1)); echo "FAIL $CASE"; printf '%b' "$DETAIL"
    echo "     --- last output ---"; printf '%s\n' "$OUT" | tail -12 | sed 's/^/     /'
  fi
  CASE=""
}
no() { CASE_OK=0; DETAIL+="     - $1\n"; }
rc() { [ "$RC" -eq "$1" ] || no "exit status $RC, wanted $1"; }
out() { case "$OUT" in *"$1"*) ;; *) no "output lacks: $1" ;; esac; }
no_out() { case "$OUT" in *"$1"*) no "output has: $1" ;; esac; }
logged() { grep -Eq -- "$1" "$T/stub/log" || no "log lacks: $1"; }
not_logged() { if grep -Eq -- "$1" "$T/stub/log"; then no "log has: $1"; fi; }
eq() { [ "$2" = "$3" ] || no "$1: got '$2', wanted '$3'"; }
ok() { local what=$1; shift; "$@" >/dev/null 2>&1 || no "$what"; }
nok() { local what=$1; shift; if "$@" >/dev/null 2>&1; then no "$what"; fi; }
restored() { eq "the three env files" "$(envsum)" "$ENV0"; nok "the saved copies are still there" test -e "$SAVED"; }
suites_run() { grep -E '^npm run -s (verify|probe):' "$T/stub/log" | grep -v 'verify:models' | awk '{print $4}' | tr '\n' ' '; }

ALL_SUITES="verify:upload verify:import verify:queue verify:frr verify:benefits verify:catalog verify:api probe:security "

# ============================================================================
# 31, F3, F4, R8. refusing
# ============================================================================
t "31 somebody's stack exists, stopped or running: refuses, names it, touches nothing"
new_sandbox
printf 'ppp-db\tExited (0) 2 hours ago\tppp\nunrelated\tUp 1 hour\tother\n' >"$T/stub/state/ps"
ft
rc 1; out "a ppp stack already exists on this machine"; out "ppp-db  (Exited (0) 2 hours ago, project ppp)"
out "Take it down yourself, then run again."; no_out "unrelated"
not_logged '^docker compose .* (up|down)'; not_logged '^npm '; not_logged '^docker (rm|network rm)'
eq "the three env files" "$(envsum)" "$ENV0"; nok "a saved directory" test -e "$SAVED"

t "F4 a stack this test left behind is told apart, and points at --restore"
new_sandbox
printf 'ppp-app\tUp 3 minutes\tppp-fulltest\nppp-db\tUp 3 minutes\tppp-fulltest\n' >"$T/stub/state/ps"
ft
rc 1; out "It is what an earlier run of this test left behind."; out "scripts/full-test.sh --restore"
no_out "Take it down yourself"; not_logged '^docker compose .* (up|down)'

t "F3 a port the stack needs is in use: refuses and names the port"
new_sandbox; EXTRA=(PPP_FULLTEST_PORTS="$FREE_PORT $BUSY_PORT")
ft
rc 1; out "port $BUSY_PORT is in use"; not_logged '^docker compose .* up'; not_logged '^npm '
eq "the three env files" "$(envsum)" "$ENV0"

t "R8 --preflight only checks: exit 0 with nothing in the way, 1 with a stack, and never starts anything"
new_sandbox
ft --preflight
rc 0; out "nothing in the way of a full test"; not_logged '^npm '; not_logged '^docker compose .* up'
printf 'ppp-app\tUp 3 hours\tppp\n' >"$T/stub/state/ps"
ft --preflight
rc 1; out "ppp-app  (Up 3 hours, project ppp)"; not_logged '^npm '; eq "the three env files" "$(envsum)" "$ENV0"

t "preflight says what is missing"
new_sandbox; rm -r "$T/repo/node_modules"
ft; rc 1; out "run npm ci first"
new_sandbox; rm "$T/repo/docker-compose.test.yml"
ft; rc 1; out "docker-compose.test.yml is missing"

# ============================================================================
# 32, 33, 39–41. the whole run
# ============================================================================
new_sandbox; EXTRA=(DB_PASSWORD=leak PPP_TAG=latest DATA_ROOT=/somewhere/else COMPOSE_PROJECT_NAME=ppp)
ft

t "32 the whole run passes and puts all three env files back, content and mode"
rc 0; restored; out "DONE failed=0"; no_out "PARTIAL RUN"
out "restored .env, .env.backup, .env.docker; stack down; logs in $LOGS"
eq "steps that passed" "$(grep -c PASS "$LOGS/summary.txt")" "19"
eq "the suites, in order" "$(suites_run)" "$ALL_SUITES"

t "39 up and down are both aimed at the project ppp-fulltest with the three files"
want='^docker compose -p ppp-fulltest --env-file \.env\.docker -f docker-compose\.prod\.yml -f docker-compose\.build\.yml -f docker-compose\.test\.yml'
logged "$want up -d --build\$"; logged "$want down -v --remove-orphans\$"; logged "$want logs --tail=300\$"
not_logged '^docker compose -p ppp '

t "39 the stack comes down while the generated .env.docker is still in place"
logged '^SEEN down .* last-line=PPP_TAG=full-test-local$'

t "40 the data directory is under the log directory and is removed through a container"
logged "^SEEN up .* DATA_ROOT=$LOGS/data "
logged "^docker run --rm -v $LOGS:/o postgres:17-alpine rm -rf /o/data\$"
nok "the data directory is still there" test -e "$LOGS/data"

t "41 the caller's DB_PASSWORD, PPP_TAG, DATA_ROOT and project name do not reach compose"
logged '^SEEN up DB_PASSWORD=unset PPP_TAG=unset '; not_logged 'leak'; not_logged '/somewhere/else'
logged '^SEEN up .* COMPOSE_PROJECT_NAME=unset '; logged '^SEEN down .* COMPOSE_PROJECT_NAME=unset '
logged '^SEEN up .* last-line=PPP_TAG=full-test-local$'

t "the secret scan runs before any env file is replaced"
logged "^SCANNED MINE=dev-env\$"
eq "position of the scan relative to up" \
  "$(grep -n -m1 '^SCANNED\|^docker compose .* up' "$T/stub/log" | head -1 | cut -d: -f2 | cut -d' ' -f1)" "SCANNED"

t "the image pins look at what this run built, under the registry the env file names"
logged '^docker run --rm --entrypoint sh ghcr\.io/octo/ppp-app:full-test-local -c command -v npm$'
logged '^docker run --rm --entrypoint sh ghcr\.io/octo/ppp-migrate:full-test-local -c \./node_modules/\.bin/prisma'
not_logged ':latest'

t "33 env files that were absent before are absent afterwards"
new_sandbox; rm "$T/repo/.env.backup"; ENV0="$(envsum)"
ft
rc 0; restored; nok ".env.backup appeared" test -e "$T/repo/.env.backup"
new_sandbox; rm "$T/repo/.env" "$T/repo/.env.backup" "$T/repo/.env.docker"; ENV0="$(envsum)"
ft
rc 0; restored; nok ".env appeared" test -e "$T/repo/.env"; nok ".env.docker appeared" test -e "$T/repo/.env.docker"

t "8 read-only env files are put back as they were, mode included"
new_sandbox; chmod 400 "$T/repo/.env" "$T/repo/.env.backup" "$T/repo/.env.docker"; ENV0="$(envsum)"
ft
rc 0; restored; eq "the mode of .env" "$(stat -c %a "$T/repo/.env")" "400"

t "8 --restore works onto a read-only env file"
new_sandbox
mkdir "$SAVED"; printf 'MINE=the-real-one\n' >"$SAVED/.env"; chmod 400 "$SAVED/.env"
printf 'GENERATED\n' >"$T/repo/.env"; chmod 400 "$T/repo/.env"
ft --restore
rc 0; eq ".env" "$(cat "$T/repo/.env")" "MINE=the-real-one"; nok "the saved copies are still there" test -e "$SAVED"

t "9 a log directory that still holds last run's data is refused, with the command that removes it"
new_sandbox; mkdir -p "$LOGS/data/db"
ft
rc 1; out "$LOGS/data already exists — the test needs a fresh data directory"
out "docker run --rm -v \"$LOGS:/o\" postgres:17-alpine rm -rf /o/data"
not_logged '^docker compose .* up'; not_logged '^npm '; eq "the three env files" "$(envsum)" "$ENV0"

t "10 a save that fails halfway changes nothing, and does not claim to have restored anything"
new_sandbox; STUBS="$BASE/stubs-cpfail"
ft
rc 1; out "could not save the env files — nothing was changed and no stack was raised"
no_out "restored .env"; no_out "stack down"
eq "the three env files" "$(envsum)" "$ENV0"; nok "half-made copies were left" test -e "$SAVED"
not_logged '^docker compose .* (up|down)'

t "10 a run killed outright in the middle of saving leaves nothing --restore could put a half file back from"
new_sandbox; STUBS="$BASE/stubs-cpfail"; touch "$T/stub/state/kill-during-save"
ft
rc 137; STUBS="$BASE/stubs"
ft --restore
rc 0; eq "the three env files" "$(envsum)" "$ENV0"; nok "the saved copies are still there" test -e "$SAVED"

t "12 the health timeout has to be a number, and --only has to name something"
new_sandbox; EXTRA=(PPP_FULLTEST_HEALTH_TIMEOUT=soon)
ft; rc 1; out "PPP_FULLTEST_HEALTH_TIMEOUT must be a whole number of seconds"; not_logged '.'
EXTRA=()
ft --only ""; rc 1; out "--only needs at least one suite"
ft --only "  "; rc 1; out "--only needs at least one suite"
ft --only; rc 1; out "--only needs a quoted list of suites"; not_logged '.'

# ============================================================================
# 34–36, F2. failures
# ============================================================================
t "34 one failing suite fails the run; the later ones still run; teardown and restore happen"
new_sandbox; touch "$T/stub/state/fail-verify:queue"
ft
rc 1; out "FAIL verify-queue (exit 1)"; out "DONE failed=1"; eq "the suites" "$(suites_run)" "$ALL_SUITES"
logged '^docker compose .* down -v --remove-orphans$'; restored
ok "the suite's log" grep -q 'this one fails' "$LOGS/verify-queue.log"

t "34 a failing static gate fails the run but does not stop it"
new_sandbox; touch "$T/stub/state/fail-typecheck"
ft
rc 1; out "FAIL typecheck (exit 1)"; eq "the suites" "$(suites_run)" "$ALL_SUITES"; restored

t "35 a stack that does not come up: no health wait, no suites, down still runs, env restored"
new_sandbox; touch "$T/stub/state/up-fail"
ft
rc 1; out "FAIL stack-up (exit 1)"; out "SKIP suites (stack did not come up)"
not_logged '^curl '; not_logged 'env:container'; eq "the suites" "$(suites_run)" ""
logged '^docker compose .* down -v --remove-orphans$'; restored

t "36 a stack that never turns healthy: FAIL health, no suites, the container logs are kept"
new_sandbox; touch "$T/stub/state/unhealthy"
ft
rc 1; out "FAIL health"; out "SKIP suites (stack not healthy)"; eq "the suites" "$(suites_run)" ""
ok "compose.log" grep -q 'container logs' "$LOGS/compose.log"; restored

t "F2 an app container that is not this run's: not one suite is run against it"
new_sandbox; echo "ppp" >"$T/stub/state/owner"
ft
rc 1; out "FAIL stack-ownership"; out "SKIP suites (the app on :3000 is not the one this run raised)"
not_logged 'env:container'; eq "the suites" "$(suites_run)" ""; restored

t "F2 if .env could not be pointed at the test stack, no suite runs"
new_sandbox; touch "$T/stub/state/fail-env:container"
ft
rc 1; out "FAIL env-container"; eq "the suites" "$(suites_run)" ""; restored

t "an image that ships npm again fails the run"
new_sandbox; touch "$T/stub/state/npm-in-image"
ft
rc 1; out "FAIL no-npm-in-images"; restored

t "F6 a data directory that cannot be removed is said, with the command, and not called clean"
new_sandbox; touch "$T/stub/state/rm-fail"
ft
out "could not remove the test data in $LOGS/data"; out "postgres:17-alpine rm -rf /o/data"
no_out "stack down;"; restored

# ============================================================================
# 37, F4. a killed run
# ============================================================================
t "37 env files a killed run left saved: refuses, and says --restore"
new_sandbox
mkdir "$SAVED"; printf 'MINE=the-real-one\n' >"$SAVED/.env"; chmod 600 "$SAVED/.env"; touch "$SAVED/.env.backup.absent"
printf 'GENERATED\n' >"$T/repo/.env"; before="$(envsum)"
ft
rc 1; out "a previous run did not restore your env files"; out "Run: scripts/full-test.sh --restore"
eq "the three env files" "$(envsum)" "$before"; ok "the saved copies" test -d "$SAVED"; not_logged '^npm '

t "37 --restore puts them back, removes what was not there, and leaves alone what was never saved"
printf 'abc123\ndef456\n' >"$T/stub/state/ps-label"; echo "net789" >"$T/stub/state/networks"
docker_env="$(cksum <"$T/repo/.env.docker")"
ft --restore
rc 0; out "restored .env, .env.backup, .env.docker"
eq ".env" "$(cat "$T/repo/.env")" "MINE=the-real-one"; eq "its mode" "$(stat -c %a "$T/repo/.env")" "600"
nok ".env.backup is still there" test -e "$T/repo/.env.backup"
eq ".env.docker, never saved" "$(cksum <"$T/repo/.env.docker")" "$docker_env"
nok "the saved copies are still there" test -e "$SAVED"

t "F4 --restore removes the leftover containers and network by label, without compose"
logged '^docker ps -aq --filter label=com\.docker\.compose\.project=ppp-fulltest$'
logged '^docker rm -f -v abc123 def456$'; logged '^docker network rm net789$'; not_logged '^docker compose -p'

t "37 --restore with nothing saved says so"
new_sandbox
ft --restore
rc 0; out "nothing to restore"; eq "the three env files" "$(envsum)" "$ENV0"; not_logged '^docker (rm|network rm)'

# ============================================================================
# 38, F1. signals
# ============================================================================
t "38 SIGTERM during a suite: the stack comes down and the env files go back"
new_sandbox; echo "verify:upload" >"$T/stub/state/term-during"
ft
rc 130; restored; logged '^docker compose .* down -v --remove-orphans$'
eq "the suites" "$(suites_run)" "verify:upload "

t "F1 a second signal during the teardown cannot skip the restore"
new_sandbox; echo "verify:upload" >"$T/stub/state/term-during"; touch "$T/stub/state/term-on-down"
ft
rc 130; restored; logged "^docker run --rm -v $LOGS:/o postgres:17-alpine rm -rf /o/data\$"

# ============================================================================
# 42, 43. partial runs, and the list of suites
# ============================================================================
t "42 without trivy: SKIP, and still exit 0"
new_sandbox; STUBS="$BASE/stubs-notrivy"
ft
rc 0; out "SKIP trivy-fs (trivy not installed; CI's trivy job still gates it)"; restored

t "42 --only runs just that suite and says PARTIAL RUN"
new_sandbox
ft --only verify:queue
rc 0; eq "the suites" "$(suites_run)" "verify:queue "; out "PARTIAL RUN — not a release gate"; restored

t "42 --only with a name that is not a suite is refused before anything starts"
new_sandbox
ft --only "verify:queue verify:nothing"
rc 1; out "verify:nothing is not one of"; not_logged '^npm '; eq "the three env files" "$(envsum)" "$ENV0"

t "F5 --no-build raises without building and says PARTIAL RUN"
new_sandbox
ft --no-build
rc 0; logged '^docker compose .* up -d$'; not_logged ' --build'; out "PARTIAL RUN — not a release gate"; restored

t "43 the suites are exactly the ones CI's verify job runs, in its order"
new_sandbox
ft
# Wherever in the job it appears — `run: npm run x` or inside a `run: |`
# block — but not in a comment.
ci="$(awk '/^  verify:$/ { on = 1; next } /^  [a-z]+:$/ { on = 0 } on && $1 !~ /^#/' "$REPO_ROOT/.github/workflows/ci.yml" \
  | grep -o 'npm run \(verify\|probe\):[a-z]*' | awk '{ print $3 }' | tr '\n' ' ')"
ok "ci.yml's verify job lists suites at all" test -n "$ci"
eq "the suites" "$(suites_run)" "$ci"

t "an unknown argument is refused, and -h prints the header"
new_sandbox
ft --fast
rc 1; out "unknown arg: --fast"; not_logged '.'
ft --help
rc 0; out "ppp full local test"; out "PPP_FULLTEST_HEALTH_TIMEOUT"; no_out "set -euo pipefail"; not_logged '.'

new_sandbox
t "across every case: no stub was asked for something it did not expect"
OUT="$(grep -n 'UNEXPECTED' "$BASE/all-logs" | head -5)"
ok "no log was collected" test -s "$BASE/all-logs"
eq "unexpected stub calls" "$(grep -c 'UNEXPECTED' "$BASE/all-logs")" "0"
eq "compose calls aimed at the project ppp" "$(grep -c '^docker compose -p ppp ' "$BASE/all-logs")" "0"
end_case

echo
echo "full-test: $PASSED passed, $FAILED failed"
[ "$FAILED" -eq 0 ]
